version: '3.9'

# demo-sequelize_mysql-1 neu khong co1 ten container no se mac dinh
services:
  mysql:
    image: mysql
    container_name: pinterest-clone-database
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=pinterest-clone
    ports:
      - 3306:3306

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pinterest-clone-server
    image: pinterest-server-image
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - mysql
    command:
      [
        "/app/wait-for",
        "pinterest-clone-database:3306",
        "--",
        "node",
        "/app/src/index.js"
      ]
